# Generated by Django 6.0.3 on 2026-03-26 04:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'), message='Price has to be a positive number')]),
        ),
    ]
