# Generated by Django 6.0.3 on 2026-03-28 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_api', '0002_alter_part_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='garage_api.manufacturer'),
        ),
        migrations.AlterField(
            model_name='part',
            name='cars',
            field=models.ManyToManyField(related_name='parts', to='garage_api.car'),
        ),
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='garage_api.manufacturer'),
        ),
    ]
